backendAzureRmResourceGroupName: 'terraform-state'
backendAzureRmResourceGroupLocation: westeurope
backendAzureRmStorageAccountName: ekterraformstate
backendAzureRmStorageAccountSku: Standard_LRS
backendAzureRmContainerName: terraform
backendAzureRmKey: terraform.tfstate
